### ISSUE TITLE
When setting a data breakpoint, Continue only does Step Into, not run.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [TheGoodDoktor/8BitAnalysers#11]
Hello,

When setting any data breakpoint, Continue only does Step Into, and no longer runs the game. When removing the data breakpoint, Continue runs the game again.

**Comment by TheGoodDoktor** [comment]
I've noticed that you have to press continue twice when it reads 16bit values. Is this what you're seeing?
I think this happens because it does 2 reads.
I'm not saying this isn't a bug (and I will fix it) I just want to make sure it's the only issue we're seeing.

**Comment by TheStruggleForAntiSpaghetti** [comment]
I just downloaded the latest May 7th version and it seems to be resolved :D
