### ISSUE TITLE
In the new 128k version, in some places "1 Bytes" is shown, instead of the data value.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [TheGoodDoktor/8BitAnalysers#13]
In the new 128k version, in some places "1 Bytes" is shown in my old file, instead of the db value.

**Comment by TheGoodDoktor** [comment]
I've seen this and put in a fix. I haven't seen it since. 
Can you check if it still happens to you with the latest version when you have a moment.
