### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [TheGoodDoktor/8BitAnalysers#2]
Hi,

While trying to build on Windows 10, I'm getting:

_8BitAnalysers-0.2.0-alpha/Source/Vendor/glfw
does not contain a CMakeLists.txt file._

My knowledge of anything C = void.

**Comment by Colourclash** [comment]
That happens if you don't clone recursively. You need to clone recursively to initialise the glfw submodule.
