### ISSUE TITLE
Step Over doesn't step over LDIR but has to be used BC times.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [TheGoodDoktor/8BitAnalysers#21]
Build: July 14th 2023
Mode: 128k (same not tested in 48k mode)

Current  behaviour:
With LDIR, `Step Over` has to be used BC times. `Step Into` has the same behaviour.

Expected behaviour:
`Step Over` to execute LDIR and go to the next line. `Step Into` has to be used to transfer for every address, BC times.

**Comment by Colourclash** [comment]
Stepping over LDIR works now
