### ISSUE TITLE
After using `New Game from Snapshot file` no code is shown.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [TheGoodDoktor/8BitAnalysers#23]
Build: July 14th 2023
Mode: 128k

After using `New Game from Snapshot file`, when entering an address to go to, nothing in the main code viewer appears. The `ROM 1` tab is selected, showing no code in the main viewer.

After selecting `RAM 0` the code there is shown. But after selecting `Jump to PC` while code is being executed in RAM 0, no code at all is shown for either `Address Space` or the ROM or RAM banks.  `Step Into` or `Step Over` doesn't show the currently executed code.

After having used `Save Game Data`, and then closing and reopening SA, everything works as expected.

**Comment by TheGoodDoktor** [comment]
I *think* I've fixed this. There was another bug relating to which memory bank tabs it showed that I put a fix in for which might also have fixed this.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Most welcome. I don't seem to have gotten a friend request from you but I've sent you one just now.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Tested on 23-11 with the latest build and it seems to be fixed. Thank you.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Fixed.
