### ISSUE TITLE
Wrong file name for kRomInfo48JsonFile

### ISSUE THREAD

**Issue by jameshpdp** [TheGoodDoktor/8BitAnalysers#33]
Hello!

Source/ZXSpectrum/SpectrumEmu.cpp [line 51](https://github.com/TheGoodDoktor/8BitAnalysers/blob/master/Source/ZXSpectrum/SpectrumEmu.cpp#L51) and 52, expect RomInfo.json and RomInfo128.json files to be available. However, provided file Data/SpectrumAnalyser/Rominfo.json has different name and cannot be loaded if copied as is. It has to have name RomInfo.json (capital "I").

**Comment by Colourclash** [comment]
I just fixed this by renaming the file Rominfo.json to RomInfo.json. Grab latest and it should be fixed

**Comment by jameshpdp** [comment]
Thank you! Surely it works as intended now.

**Comment by Colourclash** [comment]
Hope so! I'll close as fixed.
