### ISSUE TITLE
CreateDir() for Linux needs improvements

### ISSUE THREAD

**Issue by jameshpdp** [TheGoodDoktor/8BitAnalysers#34]
Hello!

The application expects a number of directories to exist, but these are not really mentioned in the "Running" section of the README. Unless the following directories are created manually, application will not be able to save any data:

- Configs
- SaveStates
- AnalysisJson
- AnalysisState
- GraphicsSets

Perhaps, adding something like

> Make sure you create appropriate directory structure in the working dir: `mkdir Configs SaveStates AnalysisJson AnalysisState GraphicsSets`

after "Copy imgui.ini from the Data/SpectrumAnalyser folder into your working dir." may help.

**Comment by Colourclash** [comment]
The code should create these directories if they don't exist, so something must not be working properly.

**Comment by jameshpdp** [comment]
Yep, I spent some time yesterday and I am afraid there is a bug in Shared/Util/Linux/FileUtil_Linux.cpp CreateDir(). If I understand it correctly, the Windows code (the most tested one) returns "false" if named path element is not a directory OR its creation was not successful. Meaning "false" is an error and "true" means directory either exists or has been created.

Linux code, however, returns "true" ONLY if supplied path element does not exist (no check for the file type). Which means it always bails out on the first ("workspace root") entry because it exists in default setup -- it's the current directory. Mac code seems to be logically correct, so a simple workaround would be to copy Mac's CreateDir implementation to Shared/Util/Linux/FileUtil_Linux.cpp -- that is working for me.

**Comment by jameshpdp** [comment]
Thanks a lot for the bugfix! Apologies, took me a while to test, but I am happy to confirm 279a120 works just fine, all directories are created when needed.
