### ISSUE TITLE
Does not build anymore on MSVC 17.8.2 (Visual Studio 2022)

### ISSUE THREAD

**Issue by kborowinski** [TheGoodDoktor/8BitAnalysers#37]
@TheGoodDoktor  8BitAnalysers does not build anymore on MSVC 17.8.2 (Visual Studio 2022)

The issue is [here](https://github.com/TheGoodDoktor/8BitAnalysers/blob/4a76cfa2cfc905819f3822454753275cfcf33f2a/Source/ZXSpectrum/CMakeLists.txt#L2). Latest version of **cmake** on fully updated Visual Studio 2022 (17.8.2) is **3.72.2-msvc1**.

**Comment by TheGoodDoktor** [comment]
Sorry, that was me messing around. I'm changed it back.
