### ISSUE TITLE
Spectrum Analyzer is unusable in high DPI screens

### ISSUE THREAD

**Issue by neuromancer** [TheGoodDoktor/8BitAnalysers#45]
The GUI is very very small in my monitor that is impossible to use. Is there any workarounds?

**Comment by Colourclash** [comment]
If you put a font in the ./Fonts directory you can tell Spectrum Analyser to use it. If you edit the GlobalConfig.json you can put the font filename in the "Font" section. You can set the font size via the "FontSizePixels" entry.

![image](https://github.com/TheGoodDoktor/8BitAnalysers/assets/883891/370723ca-13dc-4d4f-9b58-a6c531bb1346)

**Comment by Colourclash** [comment]
Latest version of Spectrum Analyser supports a TTF font, so this issue is fixed.
