### ISSUE TITLE
Outputting .ASM files sometimes mis-writes DBs

### ISSUE THREAD

**Issue by Paulie68000** [TheGoodDoktor/8BitAnalysers#49]
Occasionally when you have data between bits of code the ASM output will just output "bytes 1" in place of the DB

For example, this code is output
GameOver:
	CALL Sprint
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	1 Bytes
	LD   A,$04
	JP   PlayTune

and in analyser it shows (see screenshot)
![Screenshot_20](https://github.com/TheGoodDoktor/8BitAnalysers/assets/39914941/d3e0fb48-608a-4e8c-916d-92266c836911)

Loving the tool by the way.

**Comment by TheGoodDoktor** [comment]
Hi.
I've pushed a fix to GitHub. I managed to repro and test the fix with a different game but I'd be grateful if you could try the fix when you have a moment.
I'm glad you're enjoying the tool. Let me know if you have a feature suggestions, some of the best features have been people's suggestions and we haven't had many old-skool 8bit coders use it.

**Comment by Paulie68000** [comment]
Cheers bud, after a little fight with the Windows SDK (you need to build against Windows 11 to get stdalign.h it seems), I got it compiling, and it worked like a charm!  I've got around 80% of Cobra fully documented now, this fix should get me an output I can re-assemble shortly.  Cracking tool!  My only "wouldn't it be good if" feature would be to have the ability to search through your own comments (I find myself outputting .ASM files and then searching in there to find the rough address of what I'm after).

**Comment by TheGoodDoktor** [comment]
I've checked in a 'first draft' of a find feature, it should search comments & label names. It's on a tab next to the 'globals' tab.
80% of Cobra? - that's pretty good going! I had to implement floating bus emulation to get that bad boy working, I don't think I got very far documenting it.

**Comment by Paulie68000** [comment]
Niiice!  I believe Joff was the first person to discover the floating bus - after he left Ocean to found Special FX, the Spectrum 2a came along, with the new ULA, so one of the programmers "fixed" Cobra by replaced it with a HALT which totally buggered up the timing of the sprite draw after the push scroll.  He was not best pleased to say the least ;o)
