### ISSUE TITLE
File -> Open does not working (Windows)

### ISSUE THREAD

**Issue by tvoybro** [TheGoodDoktor/8BitAnalysers#7]
![image](https://user-images.githubusercontent.com/40628707/233833855-a507a20c-af0f-4ecf-8cc0-9713bc107d92.png)

Same thing for "New game from snapshot file"

![image](https://user-images.githubusercontent.com/40628707/233833906-382fcff8-a09b-4af3-b33f-e9378289081c.png)

UPD: same problems under Linux:

![image](https://user-images.githubusercontent.com/40628707/233835973-172e207e-1f3c-44fd-a865-4445db122a8d.png)

**Comment by Colourclash** [comment]
You need some games (.sna or .z80) in the snapshot folder. Look in globalconfig.json for the path where the snapshots should be stored. Default path is the Games folder relative to where the exe lives

**Comment by tvoybro** [comment]
That works, thanks!
